pipeline {
    agent any
        tools {
            maven 'maven-3.8.4'
        }
    stages {
        stage('Clean') {
            steps {
                sh 'mvn -f "Calculator/pom.xml" clean'
            }
        }
        stage('Static Analysis: CheckStyle') {
                    steps {
                        sh 'mvn -f "Calculator/pom.xml" checkstyle:checkstyle'
                    }
                }

        stage('Static Analysis: PMD') {
            steps {
                sh 'mvn -f "Calculator/pom.xml" pmd:pmd'
            }
        }


        stage('Test') {
            steps {
                sh 'mvn -f "Calculator/pom.xml" test'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -f "Calculator/pom.xml" package'
            }
        }

//         stage('Static Analysis: FindBugs') {
//                     steps {
//                         sh 'mvn -f "Calculator/pom.xml" clean install findbugs:findbugs'
//                     }
//                 }
        stage('Generate Reports') {
            steps {
                recordIssues(
                    enabledForFailure: true, aggregatingResults: true,
                    tools: [java(), checkStyle(pattern: 'Calculator/target/checkstyle-result.xml', reportEncoding: 'UTF-8'), pmdParser(pattern: 'Calculator/target/pmd.xml', reportEncoding: 'UTF-8')]
                )

        }

    }
    }
}