pipeline {
    agent any
        tools {
            maven 'maven-3.8.4'
        }
    stages {
        stage('Build') {
            steps {
                echo "mvn -B -DskipTests clean package"
            }
        }
    }
}